### PR TITLE
PyQt client integration

### PR DESCRIPTION
**Pull request by mdavidsaver**
A quick and dirty take of a Qt aware client `Context`.  Handles put/rpc and monitor.  Monitors are always rate limited.

The Context put/rpc/monitor methods return a QObject which emits signals w/ data or error (two separate signals).

@hhslepicka @thomascobb

### CODE REVIEW

**Comment by mdavidsaver** [comment]
Feedback from discussion with @hhslepicka

1. Beware of race condition when connecting signals after operation/subscription start.  Pass slot(s) as arguments to `Context.monitor()`.
2. Combine success/error signals as one which delivers either a Value or an Exception instance (like asyncio)
3. Should probably implement a full cache and de-duplicate subscriptions.  Too easy for naive users to create multiple identical subscriptions.  (beware of late connecting signals)
4. `Context.disconnect` conflicts with `QObject.disconnect`.

**Comment by thomascobb** [comment]
run examples/pyqt_client.py, then CTRL-C in the terminal, it will get KeyboardInterrupt on the next pv update rather than straight away

**Comment by thomascobb** [comment]
Rate limiting works as expected (highest frequency requested is delivered to all interested clients)

**Comment by mdavidsaver** [comment]
> then CTRL-C in the terminal

This appears to be a Qt/PyQt behavior which has been noted by others.

https://riverbankcomputing.com/pipermail/pyqt/2008-May/019242.html

https://coldfix.eu/2016/11/08/pyqt-boilerplate/#id2

https://stackoverflow.com/questions/1353823/handling-keyboardinterrupt-in-a-kde-python-application

The `signal.signal(signal.SIGINT, signal.SIG_DFL)` is restoring the default behavior of SIGINT, which is to terminate the process (cf `man 7 signal`).

An example of how to achieve a clean exit.

https://doc.qt.io/qt-5/unix-signals.html

**Comment by mdavidsaver** [comment]
https://github.com/mdavidsaver/p4p/pull/45

**Pull request closed without merging**
